In [122]:
import pandas as pd #usamos la libreria de pandas para tratar los datos
from sqlalchemy import create_engine

In [123]:
df1=pd.read_csv('cine.csv')
df2=pd.read_csv('museo.csv')
df3=pd.read_csv('biblioteca_popular.csv')
engine= create_engine('postgresql://postgres:123456@localhost/proyecto_alkemy')

In [124]:
df2=df2.rename(columns={
       'categoria':'Categoría', 'subcategoria':'Subcategoria', 'provincia':'Provincia', 'localidad':'Localidad', 'nombre':'Nombre',
       'direccion':'Domicilio', 'piso':'Piso','telefono':'Teléfono','fuente':'Fuente'}) #cambiamos el nombre para tener todas las columnas equivalentes
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Cod_Loc              1182 non-null   int64
 1   IdProvincia          1182 non-null   int64
 2   IdDepartamento       1182 non-null   int64
 3   Observaciones        0 non-null      float64
 4   Categoría            1182 non-null   object
 5   Subcategoria         1048 non-null   object
 6   Provincia            1182 non-null   object
 7   Localidad            1182 non-null   object
 8   Nombre               1182 non-null   object
 9   Domicilio            1164 non-null   object
 10  Piso                 0 non-null      float64
 11  CP                   1116 non-null   object
 12  cod_area             989 non-null    float64
 13  Teléfono             988 non-null    object
 14  Mail                 286 non-null    object
 15  Web                  80 non-null     object
 16  Latitud              1182 non-null   float64
 17  Longitud             1182 non-null   float64
 18  TipoLatitudLongitud  1182 non-null   object
 19  Info_adicional       10 non-null     object
 20  Fuente               1182 non-null   object
 21  jurisdiccion         1085 non-null   object
 22  año_inauguracion     643 non-null    float64
 23  IDSInCA              1182 non-null   int64
dtypes: float64(6), int64(4), object(14)
memory usage: 221.8+ KB

In [125]:
df1=df1.rename(columns={'Dirección':'Domicilio','año_actualizacion':'Año_actualizacion' }) #cambiamos el nombre para tener todas las columnas equivalentes
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Cod_Loc                329 non-null    int64
 1   IdProvincia            329 non-null    int64
 2   IdDepartamento         329 non-null    int64
 3   Observaciones          0 non-null      float64
 4   Categoría              329 non-null    object
 5   Provincia              329 non-null    object
 6   Departamento           329 non-null    object
 7   Localidad              329 non-null    object
 8   Nombre                 329 non-null    object
 9   Domicilio              329 non-null    object
 10  Piso                   329 non-null    object
 11  CP                     329 non-null    int64
 12  cod_area               329 non-null    object
 13  Teléfono               329 non-null    object
 14  Mail                   329 non-null    object
 15  Web                    329 non-null    object
 16  Información adicional  0 non-null      float64
 17  Latitud                329 non-null    float64
 18  Longitud               329 non-null    float64
 19  TipoLatitudLongitud    329 non-null    object
 20  Fuente                 329 non-null    object
 21  tipo_gestion           329 non-null    object
 22  Pantallas              329 non-null    int64
 23  Butacas                329 non-null    int64
 24  espacio_INCAA          64 non-null     object
 25  Año_actualizacion      329 non-null    int64
dtypes: float64(4), int64(7), object(15)
memory usage: 67.0+ KB

In [126]:

df3[['Cod_Loc','Fuente']].head()

    Cod_Loc   Fuente
0  70049060  CONABIP
1   2000010  CONABIP
2   2000010  CONABIP
3   2000010  CONABIP
4   2000010  CONABIP

In [127]:
fusion = [df1,df2,df3]
archivo_final = pd.concat(fusion)
archivo_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3528 entries, 0 to 2016
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Cod_Loc                3528 non-null   int64
 1   IdProvincia            3528 non-null   int64
 2   IdDepartamento         3528 non-null   int64
 3   Observaciones          0 non-null      float64
 4   Categoría              3528 non-null   object
 5   Provincia              3528 non-null   object
 6   Departamento           2346 non-null   object
 7   Localidad              3528 non-null   object
 8   Nombre                 3528 non-null   object
 9   Domicilio              3510 non-null   object
 10  Piso                   329 non-null    object
 11  CP                     3462 non-null   object
 12  cod_area               1318 non-null   object
 13  Teléfono               3334 non-null   object
 14  Mail                   2632 non-null   object
 15  Web                    409 non-null    object
 16  Información adicional  0 non-null      float64
 17  Latitud                3528 non-null   float64
 18  Longitud               3528 non-null   float64
 19  TipoLatitudLongitud    3528 non-null   object
 20  Fuente                 3528 non-null   object
 21  tipo_gestion           329 non-null    object
 22  Pantallas              329 non-null    float64
 23  Butacas                329 non-null    float64
 24  espacio_INCAA          64 non-null     object
 25  Año_actualizacion      2346 non-null   float64
 26  Subcategoria           1048 non-null   object
 27  Info_adicional         10 non-null     object
 28  jurisdiccion           1085 non-null   object
 29  año_inauguracion       643 non-null    float64
 30  IDSInCA                1182 non-null   float64
 31  Observacion            0 non-null      float64
 32  Cod_tel                2017 non-null   object
 33  Tipo_gestion           2017 non-null   object
 34  año_inicio             2010 non-null   float64
dtypes: float64(11), int64(3), object(21)
memory usage: 992.2+ KB

In [128]:
#observo que tengo columnas nulos, por lo tanto las elimino
#archivo_final.drop(archivo_final.columns[[3,16,31]], axis=1, inplace=True)
archivo_final.info()
archivo_final.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3528 entries, 0 to 2016
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Cod_Loc                3528 non-null   int64
 1   IdProvincia            3528 non-null   int64
 2   IdDepartamento         3528 non-null   int64
 3   Observaciones          0 non-null      float64
 4   Categoría              3528 non-null   object
 5   Provincia              3528 non-null   object
 6   Departamento           2346 non-null   object
 7   Localidad              3528 non-null   object
 8   Nombre                 3528 non-null   object
 9   Domicilio              3510 non-null   object
 10  Piso                   329 non-null    object
 11  CP                     3462 non-null   object
 12  cod_area               1318 non-null   object
 13  Teléfono               3334 non-null   object
 14  Mail                   2632 non-null   object
 15  Web                    409 non-null    object
 16  Información adicional  0 non-null      float64
 17  Latitud                3528 non-null   float64
 18  Longitud               3528 non-null   float64
 19  TipoLatitudLongitud    3528 non-null   object
 20  Fuente                 3528 non-null   object
 21  tipo_gestion           329 non-null    object
 22  Pantallas              329 non-null    float64
 23  Butacas                329 non-null    float64
 24  espacio_INCAA          64 non-null     object
 25  Año_actualizacion      2346 non-null   float64
 26  Subcategoria           1048 non-null   object
 27  Info_adicional         10 non-null     object
 28  jurisdiccion           1085 non-null   object
 29  año_inauguracion       643 non-null    float64
 30  IDSInCA                1182 non-null   float64
 31  Observacion            0 non-null      float64
 32  Cod_tel                2017 non-null   object
 33  Tipo_gestion           2017 non-null   object
 34  año_inicio             2010 non-null   float64
dtypes: float64(11), int64(3), object(21)
memory usage: 992.2+ KB

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,Categoría,Provincia,Departamento,Localidad,Nombre,Domicilio,...,Año_actualizacion,Subcategoria,Info_adicional,jurisdiccion,año_inauguracion,IDSInCA,Observacion,Cod_tel,Tipo_gestion,año_inicio
0,10049030,10,10049,NaN,Salas de cine,Catamarca,Capital,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10091150,10,10091,NaN,Salas de cine,Catamarca,Santa Maria,Santa María,Centro Cultural San Agustín,San Martin 173,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22140060,22,22140,NaN,Salas de cine,Chaco,San Fernando,Resistencia,Los Cines De La Costa,Av. Sarmiento 2600,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,26091020,26,26091,NaN,Salas de cine,Chubut,Sarmiento,Sarmiento,Deborah Jones De Williams,Reg. Inf. Mec. 25 Esquina 20 De Junio,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18007010,18,18007,NaN,Salas de cine,Corrientes,Bella Vista,Bella Vista,Fantasio,Salta 1059,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
archivo_final['Piso'] = archivo_final['Piso'].map({'s/d':np.nan})
archivo_final

,Cod_Loc,IdProvincia,IdDepartamento,Observaciones,Categoría,Provincia,Departamento,Localidad,Nombre,Domicilio,...,Año_actualizacion,Subcategoria,Info_adicional,jurisdiccion,año_inauguracion,IDSInCA,Observacion,Cod_tel,Tipo_gestion,año_inicio
0,10049030,10,10049,NaN,Salas de cine,Catamarca,Capital,Catamarca,Cinemacenter,Intendente Mamerto Medina 220,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10091150,10,10091,NaN,Salas de cine,Catamarca,Santa Maria,Santa María,Centro Cultural San Agustín,San Martin 173,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22140060,22,22140,NaN,Salas de cine,Chaco,San Fernando,Resistencia,Los Cines De La Costa,Av. Sarmiento 2600,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,26091020,26,26091,NaN,Salas de cine,Chubut,Sarmiento,Sarmiento,Deborah Jones De Williams,Reg. Inf. Mec. 25 Esquina 20 De Junio,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18007010,18,18007,NaN,Salas de cine,Corrientes,Bella Vista,Bella Vista,Fantasio,Salta 1059,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,62042560,62,62042,NaN,Bibliotecas Populares,Río Negro,General Roca,Villa Regina,El Progreso,Pellegrini 476,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,s/d,Comunitaria,NaN
2013,70028010,70,70028,NaN,Bibliotecas Populares,San Juan,Capital,"Villa Seminario, Rivadavia",Biblioteca Popular 23 de Septiembre,Pueyrredón 1692,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,s/d,Comunitaria,NaN
2014,62007080,62,62007,NaN,Bibliotecas Populares,Río Negro,Adolfo Alsina,San Javier,Prospero Entraigas,San Javier,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,s/d,Comunitaria,NaN
2015,62077010,62,62077,NaN,Bibliotecas Populares,Río Negro,San Antonio,Las Grutas,Cmte. Luis Piedra Buena,Villa Regina 589,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,2934,Comunitaria,NaN
2016,62042360,62,62042,NaN,Bibliotecas Populares,Río Negro,General Roca,Catriel,José Hernández,Pampa Nº 691,...,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,s/d,Comunitaria,NaN

In [130]:
#CANTIDAD DE REGISTROS TOTALES POR FUENTE

cantidad_fuente=archivo_final.groupby(['Fuente']) #con la funcion 'groupby' por podemos obtener los totales de cada columna por las categorias existentes
cantidad_fuente=cantidad_fuente.size() #obtengo la cantidad total por fuente

cantidad_fuente=pd.DataFrame(cantidad_fuente, columns=['total'])
cantidad_fuente=cantidad_fuente.reset_index()
cantidad_fuente.to_sql('cantidad_por_fuente', engine, index=False, if_exists='append')

In [131]:
#CANTIDAD DE REGISTROS TOTALES POR CATEGORIA

cantidad_categoria=archivo_final.groupby(['Categoría']) #con la funcion 'groupby' por podemos obtener los totales de cada columna por las categorias existentes
cantidad_categoria=cantidad_categoria.size() #obtengo la cantidad total por fuente

cantidad_categoria=pd.DataFrame(cantidad_categoria, columns=['total']) # con esta funcion me encargo de tranformar la serie en dataframe
cantidad_categoria=cantidad_categoria.reset_index() #Con esta opcion me encargo de tranformar el indice como columna
cantidad_categoria.to_sql('cantidad_por_categoria', engine, index=False, if_exists='append')

In [132]:
provincia_categoria=archivo_final.groupby(['Provincia', 'Categoría']) # los agrupo primero por provincia, luego por categoria
provincia_categoria=provincia_categoria.size()
cantidad
provincia_categoria=provincia_categoria.reset_index()
provincia_categoria.to_sql('cantidad_por_categoriaypronvincia', engine, index=False, if_exists='append')

In [133]:
fusion = [cantidad_fuente,cantidad_categoria,provincia_categoria]
final = pd.concat(fusion)
final.head(50)
#final[['Provincia','Categoría','Fuente','total']]

,Fuente,total,Categoría,Provincia
0,CNMLH - Enlace SInCA,1,NaN,NaN
1,CNMLH - Ente Cultural de Tucumán,1,NaN,NaN
2,CONABIP,2010,NaN,NaN
3,DNPyM,1048,NaN,NaN
4,Dirección Provincial de Patrimonio Cultural - ...,1,NaN,NaN
5,Dirección de Cultura de Villa Allende,2,NaN,NaN
6,Dirección de Cultura y de Educación de la Muni...,1,NaN,NaN
7,Gob. Pcia.,1,NaN,NaN
8,Gobierno de la Provincia,14,NaN,NaN
9,Gobierno de la Provincia de Chubut / SInCA 2013,3,NaN,NaN
10,Gobierno de la Provincia de Jujuy,4,NaN,NaN
11,Gobierno de la Provincia de La Pampa,1,NaN,NaN
12,Gobierno de la Provincia de La Rioja,1,NaN,NaN
13,Gobierno de la Provincia de Mendoza,4,NaN,NaN
14,Gobierno de la Provincia de Neuquén,1,NaN,NaN
15,Gobierno de la Provincia de Salta,1,NaN,NaN
16,Gobierno de la Provincia de San Juan,3,NaN,NaN
17,Gobierno de la provincia,1,NaN,NaN
18,INCAA / SInCA,329,NaN,NaN
19,Municipalidad de Puerto Madryn,2,NaN,NaN
20,Municipalidad de Río Gallegos - Red de Ciudade...,4,NaN,NaN
21,Municipalidad de Santa Fe - Red de Ciudades Cr...,37,NaN,NaN
22,RCC,10,NaN,NaN
23,RCC- Córdoba,31,NaN,NaN
24,Red de Espacios Culturales Vicente López,4,NaN,NaN
25,SInCA,1,NaN,NaN
26,Secretaria de Cultura Provincial,6,NaN,NaN
27,Secretaria de Cultura del Municipio de Esteban...,1,NaN,NaN
28,UNLA,1,NaN,NaN
29,Área Gestión Cultural de la Municipalidad de C...,4,NaN,NaN
0,NaN,2017,Bibliotecas Populares,NaN
1,NaN,1182,Espacios de Exhibición Patrimonial,NaN
2,NaN,329,Salas de cine,NaN
0,NaN,543,Bibliotecas Populares,Buenos Aires
1,NaN,152,Espacios de Exhibición Patrimonial,Buenos Aires
2,NaN,106,Salas de cine,Buenos Aires
3,NaN,38,Bibliotecas Populares,Catamarca
4,NaN,32,Espacios de Exhibición Patrimonial,Catamarca
5,NaN,4,Salas de cine,Catamarca
6,NaN,70,Bibliotecas Populares,Chaco
7,NaN,33,Espacios de Exhibición Patrimonial,Chaco
8,NaN,4,Salas de cine,Chaco
9,NaN,48,Bibliotecas Populares,Chubut
10,NaN,45,Espacios de Exhibición Patrimonial,Chubut
11,NaN,9,Salas de cine,Chubut
12,NaN,43,Bibliotecas Populares,Ciudad Autónoma de Buenos Aires
13,NaN,132,Espacios de Exhibición Patrimonial,Ciudad Autónoma de Buenos Aires
14,NaN,35,Salas de cine,Ciudad Autónoma de Buenos Aires
15,NaN,58,Bibliotecas Populares,Corrientes
16,NaN,14,Espacios de Exhibición Patrimonial,Corrientes